---
- name: Copy nixOS configurations
  hosts: nixos
  remote_user: alc

- name: "Copy nixOS Configuration"
  hosts: nixos
  tasks:
   - name: Copy nixOS configuration files
     ansible.builtin.copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: "{{ item.mode }}"
     with_items:
      - { src: "configuration.nix", dest: "/etc/nixos/configuration.nix", mode: "u=rw,g=r,o=r"}
      - { src: "hardware-configuration.nix", dest: "/etc/nixos/hardware-configuration.nix", mode: "u=rw,g=r,o=r"}
      - { src: "systemd.nix", dest: "/etc/nixos/systemd.nix", mode: "u=rw,g=r,o=r"}
      - { src: "services.nix", dest: "/etc/nixos/services.nix", mode: "u=rw,g=r,o=r"}
      - { src: "virtualisation.nix", dest: "/etc/nixos/virtualisation.nix", mode: "u=rw,g=r,o=r"}
      - { src: "networking.nix", dest: "/etc/nixos/networking.nix", mode: "u=rw,g=r,o=r"}
     become: true
