---
- name: Copy nixOS configuration
  hosts: nixos
  remote_user: alc

- hosts: nixos
  tasks:
  - name: Copy main nixOS configuration
    ansible.builtin.copy:
      src: configuration.nix
      dest: /etc/nixos/configuration.nix
    become: true
  - name: Copy nixOS hardware configuration
    ansible.builtin.copy:
      src: hardware-configuration.nix
      dest: /etc/nixos/hardware-configuration.nix
    become: true
  - name: Copy nixOS systemd configuration
    ansible.builtin.copy:
      src: systemd.nix
      dest: /etc/nixos/systemd.nix
    become: true
  - name: Copy nixOS services configuration
    ansible.builtin.copy:
      src: services.nix
      dest: /etc/nixos/services.nix
    become: true
  - name: Copy nixOS virtualisation configuration
    ansible.builtin.copy:
      src: virtualisation.nix
      dest: /etc/nixos/virtualisation.nix
    become: true
  - name: Copy nixOS networking configuration
    ansible.builtin.copy:
      src: networking.nix
      dest: /etc/nixos/networking.nix
    become: true