---
- name: Copy nixOS configuration
  hosts: nixos
  remote_user: alc

- hosts: nixos
  tasks:
  - name: Copy nixOS configuration
    ansible.builtin.copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items:
      - { src: "configuration.nix", dest: "/etc/nixos/configuration.nix"}
      - { src: "hardware-configuration.nix", dest: "/etc/nixos/hardware-configuration.nix"}
      - { src: "systemd.nix", dest: "/etc/nixos/systemd.nix"}
      - { src: "services.nix", dest: "/etc/nixos/services.nix"}
      - { src: "virtualisation.nix", dest: "/etc/nixos/virtualisation.nix"}
      - { src: "networking.nix", dest: "/etc/nixos/networking.nix"}
    become: true